/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class fmrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fmrPrincipal
     */
    public fmrPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btn_Trabajador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTrabajador = new javax.swing.JButton();
        btn_Tour = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnTour = new javax.swing.JButton();
        btn_Inicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btn_Paquete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnPaquete = new javax.swing.JButton();
        btn_Reserva = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        whatsapp = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        instagram = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telefono1 = new javax.swing.JLabel();
        telefono2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        btnRecomendaciones = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        pantalla1 = new javax.swing.JLabel();
        scrollLista = new javax.swing.JScrollPane();
        listaPaquete = new javax.swing.JList<>();
        txtFieldBusqueda = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Trabajador.setBackground(new java.awt.Color(63, 43, 100));

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trabajador.png"))); // NOI18N

        btnTrabajador.setBackground(new java.awt.Color(102, 0, 102));
        btnTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        btnTrabajador.setForeground(new java.awt.Color(255, 153, 0));
        btnTrabajador.setText("Trabajador");

        javax.swing.GroupLayout btn_TrabajadorLayout = new javax.swing.GroupLayout(btn_Trabajador);
        btn_Trabajador.setLayout(btn_TrabajadorLayout);
        btn_TrabajadorLayout.setHorizontalGroup(
            btn_TrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_TrabajadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_TrabajadorLayout.setVerticalGroup(
            btn_TrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_TrabajadorLayout.createSequentialGroup()
                .addGroup(btn_TrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTrabajador)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        sidePanel.add(btn_Trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 40));

        btn_Tour.setBackground(new java.awt.Color(63, 43, 100));

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tour.png"))); // NOI18N

        btnTour.setBackground(new java.awt.Color(102, 0, 102));
        btnTour.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        btnTour.setForeground(new java.awt.Color(255, 153, 0));
        btnTour.setText("Tour");

        javax.swing.GroupLayout btn_TourLayout = new javax.swing.GroupLayout(btn_Tour);
        btn_Tour.setLayout(btn_TourLayout);
        btn_TourLayout.setHorizontalGroup(
            btn_TourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_TourLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTour, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_TourLayout.setVerticalGroup(
            btn_TourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_TourLayout.createSequentialGroup()
                .addGroup(btn_TourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTour)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        sidePanel.add(btn_Tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        btn_Inicio.setBackground(new java.awt.Color(85, 55, 118));

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(102, 0, 102));
        btnInicio.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 153, 0));
        btnInicio.setText("Refrescar");

        javax.swing.GroupLayout btn_InicioLayout = new javax.swing.GroupLayout(btn_Inicio);
        btn_Inicio.setLayout(btn_InicioLayout);
        btn_InicioLayout.setHorizontalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_InicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_InicioLayout.setVerticalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addGroup(btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInicio)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        sidePanel.add(btn_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 40));

        btn_Paquete.setBackground(new java.awt.Color(63, 43, 100));

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paquete.png"))); // NOI18N

        btnPaquete.setBackground(new java.awt.Color(102, 0, 102));
        btnPaquete.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        btnPaquete.setForeground(new java.awt.Color(255, 153, 0));
        btnPaquete.setText("Paquete");

        javax.swing.GroupLayout btn_PaqueteLayout = new javax.swing.GroupLayout(btn_Paquete);
        btn_Paquete.setLayout(btn_PaqueteLayout);
        btn_PaqueteLayout.setHorizontalGroup(
            btn_PaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_PaqueteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_PaqueteLayout.setVerticalGroup(
            btn_PaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_PaqueteLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_PaqueteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPaquete)
                .addContainerGap())
        );

        sidePanel.add(btn_Paquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 40));

        btn_Reserva.setBackground(new java.awt.Color(63, 43, 100));

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reserva.png"))); // NOI18N

        btnReserva.setBackground(new java.awt.Color(102, 0, 102));
        btnReserva.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        btnReserva.setForeground(new java.awt.Color(255, 153, 0));
        btnReserva.setText("Reserva");

        javax.swing.GroupLayout btn_ReservaLayout = new javax.swing.GroupLayout(btn_Reserva);
        btn_Reserva.setLayout(btn_ReservaLayout);
        btn_ReservaLayout.setHorizontalGroup(
            btn_ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_ReservaLayout.setVerticalGroup(
            btn_ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ReservaLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserva)
                .addContainerGap())
        );

        sidePanel.add(btn_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 40));

        jLabel13.setFont(new java.awt.Font("ItalicT", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Turismo");
        jLabel13.setToolTipText("");
        sidePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, -1));

        jLabel14.setFont(new java.awt.Font("ItalicT", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Agencia");
        jLabel14.setToolTipText("");
        sidePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jLabel15.setFont(new java.awt.Font("ItalicT", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("de");
        jLabel15.setToolTipText("");
        sidePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 40, -1));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Whatsapp.png"))); // NOI18N
        sidePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        sidePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        whatsapp.setForeground(new java.awt.Color(255, 255, 255));
        whatsapp.setText("jLabel17");
        sidePanel.add(whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        facebook.setForeground(new java.awt.Color(255, 255, 255));
        facebook.setText("jLabel18");
        sidePanel.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/instagram.png"))); // NOI18N
        sidePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        instagram.setForeground(new java.awt.Color(255, 255, 255));
        instagram.setText("jLabel19");
        sidePanel.add(instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter.png"))); // NOI18N
        sidePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        twitter.setForeground(new java.awt.Color(255, 255, 255));
        twitter.setText("jLabel20");
        sidePanel.add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("Contáctenos");
        sidePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        telefono1.setForeground(new java.awt.Color(255, 255, 255));
        telefono1.setText("jLabel19");
        sidePanel.add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        telefono2.setForeground(new java.awt.Color(255, 255, 255));
        telefono2.setText("jLabel21");
        sidePanel.add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jPanel2.setBackground(new java.awt.Color(122, 71, 221));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 102));
        jLabel12.setText("Reserve su paquete");
        jLabel12.setToolTipText("");

        btn_Salir.setBackground(new java.awt.Color(204, 153, 255));
        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N

        btnNosotros.setBackground(new java.awt.Color(54, 33, 89));
        btnNosotros.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnNosotros.setForeground(new java.awt.Color(255, 255, 0));
        btnNosotros.setText("Nostros");

        btnRecomendaciones.setBackground(new java.awt.Color(54, 33, 89));
        btnRecomendaciones.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnRecomendaciones.setForeground(new java.awt.Color(255, 255, 0));
        btnRecomendaciones.setText("Recomendaciones");

        btnNotas.setBackground(new java.awt.Color(54, 33, 89));
        btnNotas.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnNotas.setForeground(new java.awt.Color(255, 255, 0));
        btnNotas.setText("Notas");

        btnConsultas.setBackground(new java.awt.Color(54, 33, 89));
        btnConsultas.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(255, 255, 0));
        btnConsultas.setText("Consultas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNosotros)
                        .addGap(39, 39, 39)
                        .addComponent(btnRecomendaciones)
                        .addGap(34, 34, 34)
                        .addComponent(btnNotas)
                        .addGap(37, 37, 37)
                        .addComponent(btnConsultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNosotros)
                            .addComponent(btnRecomendaciones)
                            .addComponent(btnNotas)
                            .addComponent(btnConsultas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 610, -1));

        jPanel1.setBackground(new java.awt.Color(122, 71, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 0));
        jLabel18.setText("Dirección");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setText("jLabel20");
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        correo.setForeground(new java.awt.Color(255, 255, 255));
        correo.setText("jLabel20");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 0));
        jLabel19.setText("Correo");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 610, 60));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        panelDerecho.setBackground(new java.awt.Color(102, 0, 102));
        panelDerecho.setPreferredSize(new java.awt.Dimension(10, 228));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("¡Vive experiencias únicas!");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Si estás buscando un poco de diversión en tus viajes");

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("No te pierdas nuestras propuestas");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(170, 170, 170))))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(panelDerecho, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(54, 33, 89));
        jPanel8.setPreferredSize(new java.awt.Dimension(611, 25));

        btnSiguiente.setBackground(new java.awt.Color(85, 55, 118));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 0));
        btnSiguiente.setText("Siguiente");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 528, Short.MAX_VALUE)
                .addComponent(btnSiguiente))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSiguiente))
        );

        jPanel3.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pantalla1.setBackground(new java.awt.Color(102, 0, 102));
        pantalla1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pantalla1.setForeground(new java.awt.Color(255, 255, 0));
        pantalla1.setText("Excursiones, actividades y paquetes turísticos para viajeros que desean ver lo mejor de Cusco");
        jPanel3.add(pantalla1, java.awt.BorderLayout.CENTER);

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 610, 90));

        listaPaquete.setBackground(new java.awt.Color(0, 102, 102));
        listaPaquete.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        listaPaquete.setForeground(new java.awt.Color(255, 255, 255));
        scrollLista.setViewportView(listaPaquete);

        bg.add(scrollLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 430, 200));
        bg.add(txtFieldBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 70, 30));

        btnBusqueda.setBackground(new java.awt.Color(0, 153, 153));
        btnBusqueda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnBusqueda.setForeground(new java.awt.Color(204, 204, 0));
        btnBusqueda.setText("Buscar");
        bg.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 80, 30));

        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPrincipal.png"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 430, 80));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pichu.gif"))); // NOI18N
        jLabel21.setText("jLabel21");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 180, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton btnBusqueda;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnInicio;
    public javax.swing.JButton btnNosotros;
    public javax.swing.JButton btnNotas;
    public javax.swing.JButton btnPaquete;
    public javax.swing.JButton btnRecomendaciones;
    public javax.swing.JButton btnReserva;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JButton btnTour;
    public javax.swing.JButton btnTrabajador;
    private javax.swing.JPanel btn_Inicio;
    private javax.swing.JPanel btn_Paquete;
    private javax.swing.JPanel btn_Reserva;
    public javax.swing.JButton btn_Salir;
    private javax.swing.JPanel btn_Tour;
    private javax.swing.JPanel btn_Trabajador;
    public javax.swing.JLabel correo;
    public javax.swing.JLabel direccion;
    public javax.swing.JLabel facebook;
    public javax.swing.JLabel instagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JList<String> listaPaquete;
    public javax.swing.JPanel panelDerecho;
    public javax.swing.JLabel pantalla1;
    public javax.swing.JScrollPane scrollLista;
    private javax.swing.JPanel sidePanel;
    public javax.swing.JLabel telefono1;
    public javax.swing.JLabel telefono2;
    public javax.swing.JLabel twitter;
    public javax.swing.JTextField txtFieldBusqueda;
    public javax.swing.JLabel whatsapp;
    // End of variables declaration//GEN-END:variables
}
