/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class fmrRegistrarTour extends javax.swing.JFrame {

    /**
     * Creates new form fmrRegistrarTour
     */
    public fmrRegistrarTour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdvertencia = new javax.swing.JButton();
        btnSalirTourFmr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtField_Lugar = new javax.swing.JTextField();
        txtField_Codigo = new javax.swing.JTextField();
        txtField_Precio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtHora = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscra = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnAgregarItinerario = new javax.swing.JButton();
        btnVerItinerario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Formulario de Tour");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 102));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 270, 10));

        btnAdvertencia.setBackground(new java.awt.Color(255, 51, 51));
        btnAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/advertencia.png"))); // NOI18N
        jPanel2.add(btnAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        btnSalirTourFmr.setBackground(new java.awt.Color(51, 0, 0));
        btnSalirTourFmr.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnSalirTourFmr.setForeground(new java.awt.Color(204, 204, 0));
        btnSalirTourFmr.setText("Salir");
        jPanel2.add(btnSalirTourFmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Lugar");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 68, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Horas");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Precio");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Código");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 249, -1, -1));
        jPanel3.add(txtField_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, -1));
        jPanel3.add(txtField_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 176, -1));
        jPanel3.add(txtField_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lugar.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, 27));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/precio.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 27));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hora.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, -1, 27));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cod.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, -1, 27));

        jLabel15.setBackground(new java.awt.Color(255, 255, 0));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("TOUR");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 6, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, 336, -1));
        jPanel3.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 360, 360));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setBackground(new java.awt.Color(51, 0, 0));
        btnModificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(204, 204, 0));
        btnModificar.setText("Modificar");
        jPanel5.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 0));
        btnEliminar.setText("Eliminar");
        jPanel5.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(51, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(204, 204, 0));
        btnAgregar.setText("Agregar");
        jPanel5.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnBuscra.setBackground(new java.awt.Color(51, 0, 0));
        btnBuscra.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnBuscra.setForeground(new java.awt.Color(204, 204, 0));
        btnBuscra.setText("Buscar");
        jPanel5.add(btnBuscra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montaña.png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 70, 70));

        btnAgregarItinerario.setBackground(new java.awt.Color(51, 0, 0));
        btnAgregarItinerario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnAgregarItinerario.setForeground(new java.awt.Color(204, 204, 0));
        btnAgregarItinerario.setText("Añadir Itinerario");
        jPanel5.add(btnAgregarItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        btnVerItinerario.setBackground(new java.awt.Color(51, 0, 0));
        btnVerItinerario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnVerItinerario.setForeground(new java.awt.Color(204, 204, 0));
        btnVerItinerario.setText("Ver Itinerario");
        jPanel5.add(btnVerItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 130, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 470, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmrRegistrarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmrRegistrarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmrRegistrarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmrRegistrarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmrRegistrarTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdvertencia;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAgregarItinerario;
    public javax.swing.JButton btnBuscra;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnSalirTourFmr;
    public javax.swing.JButton btnVerItinerario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtField_Codigo;
    public javax.swing.JTextField txtField_Lugar;
    public javax.swing.JTextField txtField_Precio;
    public javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
