/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class fmrTour extends javax.swing.JFrame {

    /**
     * Creates new form fmrTour
     */
    public fmrTour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_BuscarTour = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDetalle = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTours = new javax.swing.JTable();
        btn_Informacion = new javax.swing.JButton();
        btn_Reservar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Tiempo = new javax.swing.JMenu();
        menuItem_FullTime = new javax.swing.JMenuItem();
        menuItem_PartTime = new javax.swing.JMenuItem();
        menu_Tour = new javax.swing.JMenu();
        menuItem_Aventura = new javax.swing.JMenuItem();
        menuItem_Rural = new javax.swing.JMenuItem();
        menuItem_Naturaleza = new javax.swing.JMenuItem();
        menuItem_Negocio = new javax.swing.JMenuItem();
        menu_Inicio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lago.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 160));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel2.setText("Destino");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 300, 30));

        btn_BuscarTour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btn_BuscarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarTourActionPerformed(evt);
            }
        });
        jPanel2.add(btn_BuscarTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 210));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        txtAreaDetalle.setColumns(20);
        txtAreaDetalle.setRows(5);
        jScrollPane2.setViewportView(txtAreaDetalle);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 240, 190));

        tablaTours.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        tablaTours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lugar", "Estado", "Precio", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTours);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 480, 300));

        btn_Informacion.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btn_Informacion.setText("Información");
        jPanel1.add(btn_Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        btn_Reservar.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btn_Reservar.setText("Reservar");
        jPanel1.add(btn_Reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 120, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 100, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 100, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Detalles");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 60, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Código");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 50, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 153));

        menu_Tiempo.setText("Tiempo");

        menuItem_FullTime.setText("Full Time");
        menu_Tiempo.add(menuItem_FullTime);

        menuItem_PartTime.setText("Part Time");
        menu_Tiempo.add(menuItem_PartTime);

        jMenuBar1.add(menu_Tiempo);

        menu_Tour.setText("Tour");

        menuItem_Aventura.setText("Aventura");
        menu_Tour.add(menuItem_Aventura);

        menuItem_Rural.setText("Rural");
        menu_Tour.add(menuItem_Rural);

        menuItem_Naturaleza.setText("Naturaleza");
        menu_Tour.add(menuItem_Naturaleza);

        menuItem_Negocio.setText("Negocios");
        menu_Tour.add(menuItem_Negocio);

        jMenuBar1.add(menu_Tour);

        menu_Inicio.setText("Inicio");
        jMenuBar1.add(menu_Inicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarTourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmrTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmrTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmrTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmrTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmrTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_BuscarTour;
    public javax.swing.JButton btn_Informacion;
    public javax.swing.JButton btn_Reservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenuItem menuItem_Aventura;
    private javax.swing.JMenuItem menuItem_FullTime;
    private javax.swing.JMenuItem menuItem_Naturaleza;
    private javax.swing.JMenuItem menuItem_Negocio;
    private javax.swing.JMenuItem menuItem_PartTime;
    private javax.swing.JMenuItem menuItem_Rural;
    public javax.swing.JMenu menu_Inicio;
    public javax.swing.JMenu menu_Tiempo;
    public javax.swing.JMenu menu_Tour;
    public javax.swing.JTable tablaTours;
    public javax.swing.JTextArea txtAreaDetalle;
    // End of variables declaration//GEN-END:variables
}
