/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Contenido = new javax.swing.JPanel();
        panel_Pestañas = new javax.swing.JPanel();
        btn_Paquete = new javax.swing.JButton();
        btn_Reserva = new javax.swing.JButton();
        btn_Tour = new javax.swing.JButton();
        btn_Trabajador = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        panel_Contenido.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel_Contenido.setLayout(null);

        panel_Pestañas.setBackground(new java.awt.Color(204, 255, 153));
        panel_Pestañas.setLayout(new java.awt.CardLayout());
        panel_Contenido.add(panel_Pestañas);
        panel_Pestañas.setBounds(350, 0, 470, 460);

        btn_Paquete.setText("Paquetes");
        panel_Contenido.add(btn_Paquete);
        btn_Paquete.setBounds(20, 80, 130, 25);

        btn_Reserva.setText("Reserva");
        panel_Contenido.add(btn_Reserva);
        btn_Reserva.setBounds(20, 110, 130, 25);

        btn_Tour.setText("Tour");
        panel_Contenido.add(btn_Tour);
        btn_Tour.setBounds(20, 140, 130, 25);

        btn_Trabajador.setText("Trabajador");
        panel_Contenido.add(btn_Trabajador);
        btn_Trabajador.setBounds(20, 170, 130, 25);

        btn_Salir.setText("Salir");
        panel_Contenido.add(btn_Salir);
        btn_Salir.setBounds(30, 400, 73, 25);

        getContentPane().add(panel_Contenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Paquete;
    public javax.swing.JButton btn_Reserva;
    public javax.swing.JButton btn_Salir;
    public javax.swing.JButton btn_Tour;
    public javax.swing.JButton btn_Trabajador;
    private javax.swing.JPanel panel_Contenido;
    private javax.swing.JPanel panel_Pestañas;
    // End of variables declaration//GEN-END:variables
}
